* count the number of unique c in each b ;
%macro countof_c_by_b(filename,b,c);
	filename exTemp1 temp;
	filename exTemp2 temp;
	proc sort data=&filename.; by &b.; run;
	data exTemp1(keep=&b. &c. sortvar);
		set &filename.;
		sortvar=cat(&b.,"___",&c.);
	run;
	proc sort data=exTemp1; by sortvar; run;
	data exTemp1;
		set exTemp1;
		by sortvar;
		if first.sortvar then output;
	run;
	proc freq data=exTemp1;
		tables &b. / out=exTemp2;
	run;
	data &filename.;
		merge &filename. exTemp2(keep=&b. count rename=(count=countof_&c._by_&b.));
		by &b.;
	run;
%mend;

* a better way to doing the same ;
%macro countof_c_by_b2(filename,b,c);
	filename exTemp1 temp;
	filename exTemp2 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data exTemp1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc freq data=exTemp1;
		tables &b. / out=exTemp2;
	run;
	data &filename.;
		merge &filename. exTemp2(keep=&b. count rename=(count=countof_&c._by_&b.));
		by &b.;
	run;
%mend;

* index unique c in each b ;
%macro indx_c_by_b(filename,b,c);
	filename exTemp1 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data exTemp1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc sort data=exTemp1; by &b. &c.; run;
	data exTemp1;
		set exTemp1;
		indx_&c._by_&b. + 1;
		by &b.;
		if first.&b. then indx_&c._by_&b. = 1;
	run;
	data &filename.;
		merge &filename. exTemp1(keep=&b. &c. indx_&c._by_&b.);
		by &b.;
	run;
%mend;


* index unique c in each b ;
%macro indx_c_by_b(filename,b,c);
	filename exTemp1 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data exTemp1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc sort data=exTemp1; by &b. &c.; run;
	data exTemp1;
		set exTemp1;
		indx_&c._by_&b. + 1;
		by &b.;
		if first.&b. then indx_&c._by_&b. = 1;
	run;
	data &filename.;
		merge &filename. exTemp1(keep=&b. &c. indx_&c._by_&b.);
		by &b. &c.;
	run;
%mend;


* identify parents as pc=0 ;
%macro parent_ind(filename);
	filename exTemp1 temp;
	proc sort data=&filename.; by pin; run;
	data exTemp1(keep=pin pc);
		set &filename. (keep=pin form);
		if form="NIH TB Parent Education" then pc=0;
		*if pc=0 then output;
		if pc~=0 then delete;
	run;
	data exTemp1;
		set exTemp1;
		by pin;
		if first.pin then output;
	run;
	data &filename.;
		merge &filename. exTemp1;
		by pin;
	run;
%mend;
