* count the number of unique c in each b ;
%macro countof_c_by_b(filename,b,c);
	filename tmpf1 temp;
	filename tmpf2 temp;
	proc sort data=&filename.; by &b.; run;
	data tmpf1(keep=&b. &c. sortvar);
		set &filename.;
		sortvar=cat(&b.,"___",&c.);
	run;
	proc sort data=tmpf1; by sortvar; run;
	data tmpf1;
		set tmpf1;
		by sortvar;
		if first.sortvar then output;
	run;
	proc freq data=tmpf1;
		tables &b. / out=tmpf2;
	run;
	data &filename.;
		merge &filename. tmpf2(keep=&b. count rename=(count=countof_&c._by_&b.));
		by &b.;
	run;
%mend;

* a better way to doing the same ;
%macro countof_c_by_b2(filename,b,c);
	filename tmpf1 temp;
	filename tmpf2 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data tmpf1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc freq data=tmpf1;
		tables &b. / out=tmpf2;
	run;
	data &filename.;
		merge &filename. tmpf2(keep=&b. count rename=(count=countof_&c._by_&b.));
		by &b.;
	run;
%mend;

* index unique c in each b ;
%macro indx_c_by_b(filename,b,c);
	filename tmpf1 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data tmpf1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc sort data=tmpf1; by &b. &c.; run;
	data tmpf1;
		set tmpf1;
		indx_&c._by_&b. + 1;
		by &b.;
		if first.&b. then indx_&c._by_&b. = 1;
	run;
	data &filename.;
		merge &filename. tmpf1(keep=&b. &c. indx_&c._by_&b.);
		by &b.;
	run;
%mend;


* index unique c in each b ;
%macro indx_c_by_b(filename,b,c);
	filename tmpf1 temp;
	proc sort data=&filename.; by &b. &c.; run;
	data tmpf1;
		set &filename.(keep=&b. &c.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc sort data=tmpf1; by &b. &c.; run;
	data tmpf1;
		set tmpf1;
		indx_&c._by_&b. + 1;
		by &b.;
		if first.&b. then indx_&c._by_&b. = 1;
	run;
	data &filename.;
		merge &filename. tmpf1(keep=&b. &c. indx_&c._by_&b.);
		by &b. &c.;
	run;
%mend;


* identify parents as pc=0 ;
%macro parent_ind(filename);
	filename tmpf1 temp;
	proc sort data=&filename.; by pin; run;
	data tmpf1(keep=pin pc);
		set &filename. (keep=pin form);
		if form="NIH TB Parent Education" then pc=0;
		*if pc=0 then output;
		if pc~=0 then delete;
	run;
	data tmpf1;
		set tmpf1;
		by pin;
		if first.pin then output;
	run;
	data &filename.;
		merge &filename. tmpf1;
		by pin;
	run;
%mend;


* pick one with highest cout of d by b and c ;
%macro pick_high(filename,b,c,d,e);
	filename tmpf1 temp;
	proc sort data=&filename. out=tmpf1 ; 
		by &b. &c. &d. &e.; 
	run;
	data tmpf1(keep=&d.);
		set tmpf1 (keep=&b. &c. &d. &e.);
		by &b. &c.;
		if first.&c. then output;
	run;
	proc sort data=tmpf1; by &d.; run;
	proc sort data=&filename.; by &d.; run;
	data &filename.;
		merge &filename. tmpf1(in=kep);
		by &d.;
		if kep=1 then output;
	run;
%mend;
%pick_high(scoredata,pc,nest_id,pin,countof_form_by_pin)
